import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { ToastProvider } from "@/providers/toastify.provider";
import RouteGuard from "@/providers/routeGuard";
import { ReactQueryProvider } from "@/providers/queryClient";
import { ReduxProvider } from "@/Redux/provider";
import { CartProvider } from '@/providers/cartContex';

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fa" dir="rtl">
      <head>
        <link
          href="https://fonts.googleapis.com/css2?family=Vazirmatn&display=swap"
          rel="stylesheet"
        />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* <ReduxProvider> */}
<CartProvider>
          <ReactQueryProvider>
            <RouteGuard>
              <ToastProvider>{children}</ToastProvider>
            </RouteGuard>
          </ReactQueryProvider></CartProvider>
        {/* </ReduxProvider> */}
       
      </body>
    </html>
  );
}
